{
  "uid": "288cb8f339ec965",
  "name": "除法无效用例:0/$%%^&*",
  "fullName": "è®¡ç®å¨å®æL4.Test#test_div_error",
  "historyId": "40f13cbeb852954ac79b3deaeb9a6e52",
  "time": {
    "start": 1708412198054,
    "stop": 1708412198055,
    "duration": 1
  },
  "description": "\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a/b\n        步骤二：\n        断言a/b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        ",
  "descriptionHtml": "<pre><code>    计算器进阶功能的无效用例。\n    使用数据参数化的方法,调用getdate函数获取用例的参数。\n    步骤一：\n    计算a/b\n    步骤二：\n    断言a/b==c\n    因为输入中a或者b中包含一些无效的非整数输入，\n    所以用例将会失败。用xfail进行标记。\n</code></pre>\n",
  "status": "skipped",
  "statusMessage": "XFAIL\n\nTypeError: '>' not supported between instances of 'str' and 'int'",
  "statusTrace": "self = <homework.pytest_and_allure.计数器实战L4.testcase.计算器实战L4.Test object at 0x044CF750>\na = 0, b = '$%%^&*', c = 'TypeError'\n\n    @pytest.mark.xfail\n    @pytest.mark.advtest\n    @pytest.mark.run(order=1)\n    @allure.feature('除法功能')\n    @allure.story('除法无效场景')\n    @allure.severity(allure.severity_level.MINOR)\n    @pytest.mark.parametrize(\"a, b, c\", getdate('../datas/除法e.yaml'))\n    def test_div_error(self, a, b, c):\n        \"\"\"\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a/b\n        步骤二：\n        断言a/b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        \"\"\"\n        tester = Calculator()\n        # 动态更新用例标题，可以参与到用例执行中去增加当前用例的标题名\n        allure.dynamic.title(f\"除法无效用例:{a}/{b}\")\n        with allure.step('测试步骤一,尝试进行计算'):\n            logging.info(f'计算无效结果{a}/{b}')\n>           sum = tester.div(a, b)\n\n计算器实战L4.py:153: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <计算器.Calculator object at 0x0493BCD0>, a = 0, b = '$%%^&*'\n\n    def div(self, a, b):\n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\n..\\func\\计算器.py:11: TypeError",
  "flaky": false,
  "newFailed": false,
  "beforeStages": [
    {
      "name": "envget",
      "time": {
        "start": 1708412197831,
        "stop": 1708412197833,
        "duration": 2
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "attachmentsCount": 0,
      "shouldDisplayMessage": false,
      "stepsCount": 0,
      "hasContent": false
    }
  ],
  "testStage": {
    "description": "\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a/b\n        步骤二：\n        断言a/b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        ",
    "status": "skipped",
    "statusMessage": "XFAIL\n\nTypeError: '>' not supported between instances of 'str' and 'int'",
    "statusTrace": "self = <homework.pytest_and_allure.计数器实战L4.testcase.计算器实战L4.Test object at 0x044CF750>\na = 0, b = '$%%^&*', c = 'TypeError'\n\n    @pytest.mark.xfail\n    @pytest.mark.advtest\n    @pytest.mark.run(order=1)\n    @allure.feature('除法功能')\n    @allure.story('除法无效场景')\n    @allure.severity(allure.severity_level.MINOR)\n    @pytest.mark.parametrize(\"a, b, c\", getdate('../datas/除法e.yaml'))\n    def test_div_error(self, a, b, c):\n        \"\"\"\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a/b\n        步骤二：\n        断言a/b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        \"\"\"\n        tester = Calculator()\n        # 动态更新用例标题，可以参与到用例执行中去增加当前用例的标题名\n        allure.dynamic.title(f\"除法无效用例:{a}/{b}\")\n        with allure.step('测试步骤一,尝试进行计算'):\n            logging.info(f'计算无效结果{a}/{b}')\n>           sum = tester.div(a, b)\n\n计算器实战L4.py:153: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <计算器.Calculator object at 0x0493BCD0>, a = 0, b = '$%%^&*'\n\n    def div(self, a, b):\n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\n..\\func\\计算器.py:11: TypeError",
    "steps": [
      {
        "name": "测试步骤一,尝试进行计算",
        "time": {
          "start": 1708412198054,
          "stop": 1708412198055,
          "duration": 1
        },
        "status": "broken",
        "statusMessage": "TypeError: '>' not supported between instances of 'str' and 'int'\n",
        "statusTrace": "  File \"E:\\霍格沃茨学社\\Hogwarts-Studies\\homework\\pytest_and_allure\\计数器实战L4\\testcase\\计算器实战L4.py\", line 153, in test_div_error\n    sum = tester.div(a, b)\n          ^^^^^^^^^^^^^^^^\n  File \"E:\\霍格沃茨学社\\Hogwarts-Studies\\homework\\pytest_and_allure\\计数器实战L4\\testcase\\../func\\计算器.py\", line 11, in div\n    if a > 99 or a < -99 or b > 99 or b < -99:\n                            ^^^^^^\n",
        "steps": [],
        "attachments": [],
        "parameters": [],
        "attachmentsCount": 0,
        "shouldDisplayMessage": true,
        "stepsCount": 0,
        "hasContent": true
      }
    ],
    "attachments": [
      {
        "uid": "1acde7b05bb27250",
        "name": "log",
        "source": "1acde7b05bb27250.txt",
        "type": "text/plain",
        "size": 74
      }
    ],
    "parameters": [],
    "attachmentsCount": 1,
    "shouldDisplayMessage": true,
    "stepsCount": 1,
    "hasContent": true
  },
  "afterStages": [],
  "labels": [
    {
      "name": "severity",
      "value": "minor"
    },
    {
      "name": "feature",
      "value": "除法功能"
    },
    {
      "name": "epic",
      "value": "计算器需求"
    },
    {
      "name": "story",
      "value": "除法无效场景"
    },
    {
      "name": "tag",
      "value": "run(order=1)"
    },
    {
      "name": "tag",
      "value": "advtest"
    },
    {
      "name": "tag",
      "value": "@pytest.mark.xfail"
    },
    {
      "name": "suite",
      "value": "è®¡ç®å¨å®æL4"
    },
    {
      "name": "subSuite",
      "value": "Test"
    },
    {
      "name": "host",
      "value": "ZJS-E14"
    },
    {
      "name": "thread",
      "value": "21628-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "è®¡ç®å¨å®æL4"
    },
    {
      "name": "resultFormat",
      "value": "allure2"
    }
  ],
  "parameters": [
    {
      "name": "a",
      "value": "0"
    },
    {
      "name": "b",
      "value": "'$%%^&*'"
    },
    {
      "name": "c",
      "value": "'TypeError'"
    }
  ],
  "links": [],
  "hidden": false,
  "retry": false,
  "extra": {
    "severity": "minor",
    "retries": [],
    "categories": [],
    "tags": [
      "@pytest.mark.xfail",
      "advtest",
      "run(order=1)"
    ]
  },
  "source": "288cb8f339ec965.json",
  "parameterValues": [
    "0",
    "'$%%^&*'",
    "'TypeError'"
  ]
}