{
  "uid": "a523959f2b478d4",
  "name": "加法异常场景TypeError：hello+$%%^&*",
  "fullName": "è®¡ç®å¨å®æL4.Test#test_add_raise",
  "historyId": "4fab9fba7448d0bacf5f36e36f21ea09",
  "time": {
    "start": 1708412218562,
    "stop": 1708412219564,
    "duration": 1002
  },
  "description": "\n        计算器进阶功能的异常处理用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a+b\n        步骤二：\n        断言errinfo.type is TypeError\n        因为输入中a或者b中包含一些无效的非整数输入，应该抛出TypeError。\n        用异常捕获的方法来判断的异常是否符合预期，对于其他异常将抛出失败。\n        c变量用参数化来传入异常类型。\n        ",
  "descriptionHtml": "<pre><code>    计算器进阶功能的异常处理用例。\n    使用数据参数化的方法,调用getdate函数获取用例的参数。\n    步骤一：\n    计算a+b\n    步骤二：\n    断言errinfo.type is TypeError\n    因为输入中a或者b中包含一些无效的非整数输入，应该抛出TypeError。\n    用异常捕获的方法来判断的异常是否符合预期，对于其他异常将抛出失败。\n    c变量用参数化来传入异常类型。\n</code></pre>\n",
  "status": "passed",
  "flaky": false,
  "newFailed": false,
  "beforeStages": [
    {
      "name": "envget",
      "time": {
        "start": 1708412197831,
        "stop": 1708412197833,
        "duration": 2
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "attachmentsCount": 0,
      "shouldDisplayMessage": false,
      "stepsCount": 0,
      "hasContent": false
    }
  ],
  "testStage": {
    "description": "\n        计算器进阶功能的异常处理用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a+b\n        步骤二：\n        断言errinfo.type is TypeError\n        因为输入中a或者b中包含一些无效的非整数输入，应该抛出TypeError。\n        用异常捕获的方法来判断的异常是否符合预期，对于其他异常将抛出失败。\n        c变量用参数化来传入异常类型。\n        ",
    "status": "passed",
    "steps": [
      {
        "name": "测试步骤一,尝试进行计算",
        "time": {
          "start": 1708412218562,
          "stop": 1708412218563,
          "duration": 1
        },
        "status": "passed",
        "steps": [],
        "attachments": [],
        "parameters": [],
        "attachmentsCount": 0,
        "shouldDisplayMessage": false,
        "stepsCount": 0,
        "hasContent": false
      },
      {
        "name": "测试步骤二,判断抛出的异常是否为预知的异常报错",
        "time": {
          "start": 1708412218563,
          "stop": 1708412218563,
          "duration": 0
        },
        "status": "passed",
        "steps": [],
        "attachments": [],
        "parameters": [],
        "attachmentsCount": 0,
        "shouldDisplayMessage": false,
        "stepsCount": 0,
        "hasContent": false
      }
    ],
    "attachments": [
      {
        "uid": "c8e136be2bfa9203",
        "name": "log",
        "source": "c8e136be2bfa9203.txt",
        "type": "text/plain",
        "size": 178
      }
    ],
    "parameters": [],
    "attachmentsCount": 1,
    "shouldDisplayMessage": false,
    "stepsCount": 2,
    "hasContent": true
  },
  "afterStages": [],
  "labels": [
    {
      "name": "story",
      "value": "加法异常场景"
    },
    {
      "name": "severity",
      "value": "trivial"
    },
    {
      "name": "epic",
      "value": "计算器需求"
    },
    {
      "name": "feature",
      "value": "加法功能"
    },
    {
      "name": "tag",
      "value": "advtest"
    },
    {
      "name": "suite",
      "value": "è®¡ç®å¨å®æL4"
    },
    {
      "name": "subSuite",
      "value": "Test"
    },
    {
      "name": "host",
      "value": "ZJS-E14"
    },
    {
      "name": "thread",
      "value": "21628-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "è®¡ç®å¨å®æL4"
    },
    {
      "name": "resultFormat",
      "value": "allure2"
    }
  ],
  "parameters": [
    {
      "name": "a",
      "value": "'hello'"
    },
    {
      "name": "b",
      "value": "'$%%^&*'"
    },
    {
      "name": "c",
      "value": "'TypeError'"
    }
  ],
  "links": [],
  "hidden": false,
  "retry": false,
  "extra": {
    "severity": "trivial",
    "retries": [],
    "categories": [],
    "tags": [
      "advtest"
    ]
  },
  "source": "a523959f2b478d4.json",
  "parameterValues": [
    "'hello'",
    "'$%%^&*'",
    "'TypeError'"
  ]
}